# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_calculate_count_dict <- function(count_vec) {
    .Call(`_nbcf_rcpp_calculate_count_dict`, count_vec)
}

rcpp_hello_world <- function() {
    .Call(`_nbcf_rcpp_hello_world`)
}

