# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_calculate_count_dict <- function(count_vec) {
    .Call(`_nbcf_rcpp_calculate_count_dict`, count_vec)
}

rcpp_calculate_lnb_values <- function(count_vec, p_vec, r) {
    .Call(`_nbcf_rcpp_calculate_lnb_values`, count_vec, p_vec, r)
}

rcpp_calculate_p_dict <- function(p_vec, mean_bias_vec) {
    .Call(`_nbcf_rcpp_calculate_p_dict`, p_vec, mean_bias_vec)
}

